In [1]:
#import all the required package
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,precision_score,recall_score,roc_auc_score,f1_score,accuracy_score
from sklearn import model_selection
from sklearn.model_selection import cross_val_score

In [2]:
#import the dataset
input_df=pd.read_csv(r"/content/audit_risk.csv")


In [3]:
#size of the dataset
print(input_df.shape)

(776, 27)


In [4]:
print(input_df.isna().sum())

Sector_score      0
LOCATION_ID       0
PARA_A            0
Score_A           0
Risk_A            0
PARA_B            0
Score_B           0
Risk_B            0
TOTAL             0
numbers           0
Score_B.1         0
Risk_C            0
Money_Value       1
Score_MV          0
Risk_D            0
District_Loss     0
PROB              0
RiSk_E            0
History           0
Prob              0
Risk_F            0
Score             0
Inherent_Risk     0
CONTROL_RISK      0
Detection_Risk    0
Audit_Risk        0
Risk              0
dtype: int64


In [6]:
print(input_df.duplicated().any())

True


In [7]:
print(input_df.drop_duplicates(inplace=True))

None


In [8]:
input_df.loc[input_df['LOCATION_ID']=='LOHARU','LOCATION_ID']=45
input_df.loc[input_df['LOCATION_ID']=='NUH','LOCATION_ID']=46
input_df.loc[input_df['LOCATION_ID']=='SAFIDON','LOCATION_ID']=47

In [9]:
input_df['LOCATION_ID']=input_df['LOCATION_ID'].astype(str)
input_df['LOCATION_ID']=input_df['LOCATION_ID'].astype(int)

In [10]:
input_df['Money_Value'].fillna((input_df['Money_Value'].mean()),inplace=True)
#total is just thee total of para_A and para_b
#since the detection_risk has no co relation value we are dropping it.
input_df.drop(columns=['TOTAL','Detection_Risk'],inplace=True)
X=input_df.drop(columns='Risk')
y=input_df['Risk']

In [11]:
sc=StandardScaler()
X1=sc.fit_transform(X)
X1_new=pd.DataFrame(X1)

In [12]:
#splitting train and text data
xtrain,xtest,ytrain,ytest=train_test_split(X1_new,y)

In [26]:
#prediction for train data using decision tree
ypred6=model2.predict(xtrain)
np.mean(ytrain==ypred6)


0.965034965034965

In [27]:
#confusion matrix from KNN test data
confusion_matrix(ytest,ypred3)

array([[109,   3],
       [  3,  76]])

In [28]:
ypred6=model2.predict(xtrain)
np.mean(ytrain==ypred6)

0.965034965034965

In [39]:
#model evaluation
acc_rf=accuracy_score(ytest,ypred7)
prec_rf=precision_score(ytest,ypred7)
rec_rf=recall_score(ytest,ypred7)
f1_rf=f1_score(ytest,ypred7)
roc_rf=roc_auc_score(ytest,ypred7)
results_rf= pd.DataFrame([['Random forest',acc_rf, acc_rf.mean(),prec_rf,rec_rf, f1_rf,roc_rf]],
               columns = ['Model', 'Accuracy','Cross Val Accuracy', 'Precision', 'Recall', 'F1 Score','ROC'])
results=results.append(results_rf,ignore_index=True)
results

Model  Accuracy  Cross Val Accuracy  Precision    Recall  \
0  Logistic Regression  0.973822            0.982547   0.940476  1.000000   
1                  KNN  0.968586            0.968586   0.962025  0.962025   
2        Random forest  1.000000            1.000000   1.000000  1.000000   
3        Random forest  1.000000            1.000000   1.000000  1.000000   

   F1 Score       ROC  
0  0.969325  0.977679  
1  0.962025  0.967620  
2  1.000000  1.000000  
3  1.000000  1.000000

In [40]:
#predict train data using randomforest
ypred8=model4.predict(xtrain)
accuracy_score(ytrain,ypred8)

1.0

In [44]:
#confusion matrix from randomforest test data
confusion_matrix(ytest,ypred7)

array([[112,   0],
       [  0,  79]])

In [45]:
#confusion matrix from randomforest train data
confusion_matrix(ytrain,ypred8)

array([[347,   0],
       [  0, 225]])

In [42]:
#implimenting random forest
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,criterion='gini')
model4=rf.fit(xtrain,ytrain)
ypred7=model4.predict(xtest)

In [32]:
#impliment logistic regression
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()
model1=lg.fit(xtrain,ytrain)
ypred1=model1.predict(xtest)

In [35]:
#cross validation
kfold = model_selection.KFold(n_splits=10, random_state=None)
scoring = 'accuracy'

acc_rf = cross_val_score(estimator = rf, X = xtrain, y = ytrain, cv = kfold,scoring=scoring)
acc_rf.mean()

0.9982456140350877

In [18]:
#cross validation
kfold = model_selection.KFold(n_splits=10, random_state='default')
scoring = 'accuracy'
acc_logi = cross_val_score(estimator = lg, X = xtrain, y = ytrain, cv = kfold,scoring=scoring)
acc_logi.mean()

0.9825468844525105

In [19]:
#model evaluation
acc=accuracy_score(ytest,ypred1)
prec=precision_score(ytest,ypred1)
rec=recall_score(ytest,ypred1)
f1=f1_score(ytest,ypred1)
roc=roc_auc_score(ytest,ypred1)
results= pd.DataFrame([['Logistic Regression',acc, acc_logi.mean(),prec,rec, f1,roc]],
               columns = ['Model', 'Accuracy','Cross Val Accuracy', 'Precision', 'Recall', 'F1 Score','ROC'])
results

Model  Accuracy  Cross Val Accuracy  Precision  Recall  \
0  Logistic Regression  0.973822            0.982547   0.940476     1.0   

   F1 Score       ROC  
0  0.969325  0.977679

In [20]:
#prediction for train data using logistic regression
ypred2=model1.predict(xtrain)
np.mean(ytrain==ypred2)

0.9877622377622378

In [21]:
#confusion matrix from Logistic regression train data
confusion_matrix(ytrain,ypred2)

array([[347,   0],
       [  7, 218]])

In [22]:
#implimenting knn 
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
model2=knn.fit(xtrain,ytrain)
ypred3=model2.predict(xtest)

In [24]:
#cross validation
kfold = model_selection.KFold(n_splits=10, random_state=None)
scoring = 'accuracy'

acc_knn = cross_val_score(estimator = knn, X = xtrain, y = ytrain, cv = kfold,scoring=scoring)
acc_knn.mean()

0.9580459770114942

In [25]:
acc_knn=accuracy_score(ytest,ypred3)
prec_knn=precision_score(ytest,ypred3)
rec_knn=recall_score(ytest,ypred3)
f1_knn=f1_score(ytest,ypred3)
roc_knn=roc_auc_score(ytest,ypred3)
results_knn= pd.DataFrame([['KNN',acc_knn, acc_knn.mean(),prec_knn,rec_knn, f1_knn,roc_knn]],
               columns = ['Model', 'Accuracy','Cross Val Accuracy', 'Precision', 'Recall', 'F1 Score','ROC'])
results=results.append(results_knn,ignore_index=True)
results

Model  Accuracy  Cross Val Accuracy  Precision    Recall  \
0  Logistic Regression  0.973822            0.982547   0.940476  1.000000   
1                  KNN  0.968586            0.968586   0.962025  0.962025   

   F1 Score       ROC  
0  0.969325  0.977679  
1  0.962025  0.967620